services:
  spark-master:
    image: apache/spark:3.5.3
    container_name: spark-master-pj
    hostname: spark-master
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"]
    volumes:
    - ./data:/opt/spark/work-dir/data
    - ./app:/opt/spark/work-dir/app
    ports:
      - "7077:7077"   # Port du master pour spark-submit
      - "8080:8080"   # UI du master
    networks:
      - spark-net

  spark-worker-1:
    image: apache/spark:3.5.3
    container_name: spark-worker-pj-1
    hostname: spark-worker-1
    volumes:
      - ./data:/opt/spark/work-dir/data
      - ./app:/opt/spark/work-dir/app
    depends_on:
      - spark-master
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]
    networks:
      - spark-net

  spark-worker-2:
    image: apache/spark:3.5.3
    container_name: spark-worker-pj-2
    hostname: spark-worker-2
    volumes:
      - ./data:/opt/spark/work-dir/data
      - ./app:/opt/spark/work-dir/app
    depends_on:
      - spark-master
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]
    networks:
      - spark-net

networks:
  spark-net:
    driver: bridge
